all:
	gcc -o serverA serverA.c
	gcc -o serverB serverB.c
	gcc -o servermain servermain.c
	gcc -o client client.c
serverA:
	gcc -o serverA serverA.c
serverB:
	gcc -o serverB serverB.c
servermain:
	gcc -o servermain servermain.c
client:
	gcc -o client client.c